#!/bin/bash

echo "🚀 Zen Therapy - Quick Deployment"
echo "=================================="

echo ""
echo "✅ Code pushed to GitHub: https://github.com/nicole-mathias/therapyApp"
echo ""

echo "📋 Next Steps:"
echo ""
echo "1. 🚂 Deploy Backend (Railway):"
echo "   - Go to: https://railway.app"
echo "   - Create new project"
echo "   - Deploy from GitHub repo"
echo "   - Add PostgreSQL database"
echo "   - Set environment variables:"
echo "     DATABASE_URL=your_railway_postgresql_url"
echo "     HUGGINGFACE_API_TOKEN=hf_your_token_here"
echo "     ALLOWED_ORIGINS=https://zen-therapy.vercel.app"
echo ""
echo "2. 🎨 Deploy Frontend (Vercel):"
echo "   - Go to: https://vercel.com"
echo "   - Import GitHub repository"
echo "   - Set root directory: frontend"
echo "   - Set environment variables:"
echo "     REACT_APP_API_URL=https://your-railway-app.railway.app"
echo "     REACT_APP_NAME=Zen Therapy"
echo ""
echo "3. 🔗 Get your URLs:"
echo "   - Backend: https://your-app.railway.app"
echo "   - Frontend: https://your-app.vercel.app"
echo ""
echo "📖 See DEPLOYMENT.md for detailed instructions"
echo ""
echo "🎯 Your app will be live and professional!" 